export { HarnessError, EXIT_CODES, type HarnessErrorCode } from "./errors";
export { HARNESS_VERSION } from "./version";
export { buildFileIndex, type FileIndex } from "./fsindex";
export { scan, type ScanOptions } from "./scan";
export { gitCommitCount } from "./gitinfo";
export { loadConfig, type LoadedConfig, HARNESS_DIR, CONFIG_PATH, MANIFEST_PATH, MAP_PATH, DOCS_DIR } from "./config";
export { buildMap, type BuildMapOptions } from "./graph/build";
export * from "./artifacts/index";
export { inferRiskAreas, effectiveRiskAreas } from "./risk/areas";
export { changedFiles, parseDiff, requireGitRepo, type ParsedDiffFile } from "./git";
export { planVerify, type VerifyPlan, type VerifyScope } from "./verify/plan";
export { runVerify, type RunVerifyOptions } from "./verify/run";
export { parseFailures } from "./verify/parsers";
export { nameMatchesSource } from "./graph/testmap";
export { classifyRole } from "./graph/roles";
export { computeInputsHash, isTrackedInput } from "./hash";
export { isManagedPath } from "./managed";
