import { createHash } from "node:crypto";
import { HARNESS_VERSION } from "../version";

export interface ArtifactBlock {
  id: string;
  /** Hash of the facts this block renders — refresh rewrites only on mismatch. */
  inputs: string;
  /** Rendered markdown, no markers. */
  content: string;
}

export interface GeneratedArtifact {
  id: string;
  /** Repo-relative target path. */
  path: string;
  blocks: ArtifactBlock[];
  /** managed-file: harness owns the whole file. managed-blocks: only marker blocks (file may hold user content). */
  ownership: "managed-file" | "managed-blocks";
  lineBudget: number;
  warnings: string[];
}

export class BlockCorruptionError extends Error {
  constructor(
    readonly path: string,
    detail: string,
  ) {
    super(`corrupted rh marker blocks in ${path}: ${detail}`);
    this.name = "BlockCorruptionError";
  }
}

export function blockHash(data: unknown): string {
  return createHash("sha256").update(JSON.stringify(data)).digest("hex").slice(0, 12);
}

export function fileHeader(manifestHash: string): string {
  return `<!-- generated by repo-harness v${HARNESS_VERSION} · ${manifestHash} · do not edit inside rh blocks -->`;
}

const BEGIN_RE = /^<!-- rh:begin id=([\w-]+) inputs=([\w]+) -->$/;
const END = "<!-- rh:end -->";
const HEADER_RE = /^<!-- generated by repo-harness .* -->$/;

function renderBlock(b: ArtifactBlock): string {
  return `<!-- rh:begin id=${b.id} inputs=${b.inputs} -->\n${b.content}\n${END}`;
}

type Segment = { kind: "text"; lines: string[] } | { kind: "block"; id: string; inputs: string; lines: string[] };

function parseSegments(path: string, content: string): Segment[] {
  const segments: Segment[] = [];
  let current: Segment = { kind: "text", lines: [] };
  for (const line of content.split("\n")) {
    const begin = line.match(BEGIN_RE);
    if (begin) {
      if (current.kind === "block") throw new BlockCorruptionError(path, `nested begin for id=${begin[1]}`);
      segments.push(current);
      current = { kind: "block", id: begin[1]!, inputs: begin[2]!, lines: [] };
      continue;
    }
    if (line.trim() === END) {
      if (current.kind !== "block") throw new BlockCorruptionError(path, "rh:end without rh:begin");
      segments.push(current);
      current = { kind: "text", lines: [] };
      continue;
    }
    current.lines.push(line);
  }
  if (current.kind === "block") throw new BlockCorruptionError(path, `rh:begin id=${current.id} never closed`);
  segments.push(current);
  return segments;
}

function freshRender(artifact: GeneratedArtifact, manifestHash: string): string {
  const parts = artifact.ownership === "managed-file" ? [fileHeader(manifestHash)] : [];
  for (const b of artifact.blocks) parts.push(renderBlock(b));
  return `${parts.join("\n\n")}\n`;
}

/**
 * Compute the new file content: user text outside blocks is preserved verbatim;
 * blocks are replaced only when their inputs hash changed; blocks the artifact
 * dropped are removed (managed-file) or left (managed-blocks); new blocks append.
 * Throws BlockCorruptionError on unbalanced markers — callers surface path + fix.
 */
export function mergeArtifact(existing: string | null, artifact: GeneratedArtifact, manifestHash: string): string {
  if (existing === null) return freshRender(artifact, manifestHash);
  const segments = parseSegments(artifact.path, existing);
  const wanted = new Map(artifact.blocks.map((b) => [b.id, b]));
  const emitted = new Set<string>();
  const out: string[] = [];

  for (const seg of segments) {
    if (seg.kind === "text") {
      for (const line of seg.lines) {
        if (HEADER_RE.test(line) && artifact.ownership === "managed-file") out.push(fileHeader(manifestHash));
        else out.push(line);
      }
      continue;
    }
    const next = wanted.get(seg.id);
    if (!next) {
      if (artifact.ownership === "managed-blocks") out.push(renderBlock({ id: seg.id, inputs: seg.inputs, content: seg.lines.join("\n") }));
      continue; // managed-file: stale block dropped
    }
    emitted.add(seg.id);
    out.push(seg.inputs === next.inputs ? renderBlock({ ...next, content: seg.lines.join("\n") }) : renderBlock(next));
  }
  for (const b of artifact.blocks) {
    if (!emitted.has(b.id)) out.push(renderBlock(b));
  }
  let joined = out.join("\n");
  if (!joined.endsWith("\n")) joined += "\n";
  return joined;
}

/** Which block ids would be rewritten (used by refresh --check and reporting). */
export function staleBlockIds(existing: string | null, artifact: GeneratedArtifact): string[] {
  if (existing === null) return artifact.blocks.map((b) => b.id);
  let segments: Segment[];
  try {
    segments = parseSegments(artifact.path, existing);
  } catch {
    return artifact.blocks.map((b) => b.id);
  }
  const current = new Map<string, string>();
  for (const seg of segments) if (seg.kind === "block") current.set(seg.id, seg.inputs);
  return artifact.blocks.filter((b) => current.get(b.id) !== b.inputs).map((b) => b.id);
}
