import { HARNESS_VERSION, blockHash, type DocContext, type GeneratedArtifact } from "@iknowkungfu/core";
import type { Client } from "@iknowkungfu/schemas";

export const MCP_JSON_SNIPPET = `{"mcpServers":{"iknowkungfu":{"command":"iknowkungfu","args":["mcp"]}}}`;

const SHIM_BUDGET = 30;

function shim(
  id: string,
  path: string,
  ownership: GeneratedArtifact["ownership"],
  content: string,
): GeneratedArtifact {
  const warnings: string[] = [];
  if (content.split("\n").length > SHIM_BUDGET) warnings.push(`${path} over shim budget (${SHIM_BUDGET} lines)`);
  if (ownership === "owned-verbatim") {
    return { id, path, blocks: [], ownership, verbatim: content, lineBudget: SHIM_BUDGET, warnings };
  }
  return {
    id,
    path,
    blocks: [{ id, inputs: blockHash(content), content }],
    ownership,
    lineBudget: SHIM_BUDGET,
    warnings,
  };
}

function agentsMd(): GeneratedArtifact {
  return shim(
    "agents-md",
    "AGENTS.md",
    "managed-blocks",
    [
      "# Agent instructions (generated by iknowkungfu — run `iknowkungfu refresh` if stale)",
      "1. Read `.iknowkungfu/docs/PROJECT_CONTEXT.md` for structure and EXACT commands.",
      "2. Follow the loop in `.iknowkungfu/docs/AGENT_RUNBOOK.md` — verify before and after edits.",
      "3. Check `.iknowkungfu/docs/REFACTOR_GUARDRAILS.md` before touching listed risk areas.",
      "4. Validate with `iknowkungfu verify --changed`; gate commits with `iknowkungfu risk --staged`.",
      "5. If the `iknowkungfu` MCP server is available, prefer its tools over manual exploration.",
      "",
      "Facts tagged `⚠ inferred` or `🤖 llm` need verification; untagged facts are parsed from config — trust them.",
    ].join("\n"),
  );
}

function claudeMd(): GeneratedArtifact {
  return shim(
    "claude",
    "CLAUDE.md",
    "managed-blocks",
    [
      "@AGENTS.md",
      "",
      `MCP: register the harness server by merging this into \`.mcp.json\`: \`${MCP_JSON_SNIPPET}\``,
    ].join("\n"),
  );
}

function codexSkill(): GeneratedArtifact {
  return shim(
    "codex",
    ".codex/skills/iknowkungfu/SKILL.md",
    "owned-verbatim",
    [
      "---",
      "name: iknowkungfu",
      "description: Use for ANY task in this repo — precomputed project context, exact commands,",
      "  verification workflow, and risk guardrails.",
      "---",
      "",
      `# iknowkungfu (generated by iknowkungfu v${HARNESS_VERSION} — do not edit)`,
      "",
      "Before any work: read `.iknowkungfu/docs/PROJECT_CONTEXT.md` (facts + exact commands) and follow",
      "`.iknowkungfu/docs/AGENT_RUNBOOK.md` (workflow). Verify changes: `iknowkungfu verify --changed`.",
      "Risk gate before commit: `iknowkungfu risk --staged`. Task recipes: `.iknowkungfu/docs/PROMPTS.md`.",
      "Never guess a command that isn't in the catalog; never edit inside `rh:` marker blocks.",
      "",
    ].join("\n"),
  );
}

function cursorRule(): GeneratedArtifact {
  return shim(
    "cursor",
    ".cursor/rules/iknowkungfu.mdc",
    "owned-verbatim",
    [
      "---",
      "description: iknowkungfu — project context, exact commands, verification workflow",
      "alwaysApply: true",
      "---",
      "",
      "Read @.iknowkungfu/docs/PROJECT_CONTEXT.md for structure and exact commands.",
      "Follow @.iknowkungfu/docs/AGENT_RUNBOOK.md. Risk areas: @.iknowkungfu/docs/REFACTOR_GUARDRAILS.md.",
      "Verify every change with `iknowkungfu verify --changed`; gate commits with `iknowkungfu risk --staged`.",
      "",
    ].join("\n"),
  );
}

function copilotInstructions(): GeneratedArtifact {
  return shim(
    "copilot",
    ".github/copilot-instructions.md",
    "managed-blocks",
    [
      "This repo uses iknowkungfu. Project facts and exact build/test/lint commands:",
      "`.iknowkungfu/docs/PROJECT_CONTEXT.md`. Workflow: `.iknowkungfu/docs/AGENT_RUNBOOK.md`.",
      "Validate changes with `iknowkungfu verify --changed`. Do not invent commands.",
    ].join("\n"),
  );
}

const REGISTRY: Record<Client, (ctx: DocContext) => GeneratedArtifact> = {
  "agents-md": agentsMd,
  claude: claudeMd,
  codex: codexSkill,
  cursor: cursorRule,
  copilot: copilotInstructions,
};

export function adapterArtifact(client: Client, ctx: DocContext): GeneratedArtifact {
  return REGISTRY[client](ctx);
}

export function adapterPath(client: Client): string {
  // Paths are static per client; build a throwaway artifact to read them.
  return REGISTRY[client]({} as DocContext).path;
}
